#!/bin/python3
# -*- coding: utf-8 -*-
"""day11_exercices_sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18rhI6qGnewUc_Hrla7sRxllQ34iMVYco

# Sets
"""

# 1) Create an empty set and assign it to a variable.
empty_set = set()
print(empty_set)

# 2) Add three items to your empty set using either several add calls, or a single call to update.
empty_set.add("item1")
empty_set.update({"item2", "item3"})
print(empty_set)

# 3) Create a second set which includes at least one common element with the first set.
second_set = set({"item1","uwu"})
print(second_set)

# 4) Find the union, symmetric difference, and intersection of the two sets. Print the results of each operation.
print(f'union: {empty_set.union(second_set)}')
print(f'symmetric difference: {empty_set.symmetric_difference(second_set)}')
print(f'intersection: {empty_set.intersection(second_set)}')

# 5) Create a sequence of numbers using range, then ask the user to enter a number. Inform the user whether or not their number was within the range you specified.
numbers = set(range(1,100))
user_num = int(input('Please, enter a number: '))
if (user_num in numbers):
  print(f'The number: {user_num} is in the range of the set')
else:
  print(f'The number: {user_num} is NOT in the range of the set')